apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-ingress
  namespace: notes-app-ns
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  # القاعدة الأولى: (بدون سطر host)
  # دي هتصطاد أي ترافيك جاي من رابط AWS الطويل أو أي رابط مش متعرف
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notes-app-service
            port:
              number: 80

  # القاعدة التانية: دي مخصصة ليك أنت لما تستخدم الدومين الوهمي
  - host: notes.hassan.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notes-app-service
            port:
              number: 80