apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: notes-app-ns
spec:
  type: LoadBalancer
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 80         # البورت الخارجي الذي سيدخل منه المستخدمون
      targetPort: 5000 # البورت الداخلي لتطبيق Flask